<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CurrenciesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('currencies')->delete();
        
        \DB::table('currencies')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Afghani',
                'code' => 'AFN',
                'symbol_left' => '؋',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Lek',
                'code' => 'ALL',
                'symbol_left' => 'Lek',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Netherlands Antillian Guilder',
                'code' => 'ANG',
                'symbol_left' => 'ƒ',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Argentine Peso',
                'code' => 'ARS',
                'symbol_left' => '$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Australian Dollar',
                'code' => 'AUD',
                'symbol_left' => '$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Aruban Guilder',
                'code' => 'AWG',
                'symbol_left' => 'ƒ',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Azerbaijanian Manat',
                'code' => 'AZN',
                'symbol_left' => 'ман',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Convertible Marks',
                'code' => 'BAM',
                'symbol_left' => 'KM',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Bangladeshi Taka',
                'code' => 'BDT',
                'symbol_left' => '৳',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Barbados Dollar',
                'code' => 'BBD',
                'symbol_left' => '$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Bulgarian Lev',
                'code' => 'BGN',
                'symbol_left' => 'лв',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Bermudian Dollar',
                'code' => 'BMD',
                'symbol_left' => '$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Brunei Dollar',
                'code' => 'BND',
                'symbol_left' => '$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'BOV Boliviano Mvdol',
                'code' => 'BOB',
                'symbol_left' => '$b',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Brazilian Real',
                'code' => 'BRL',
                'symbol_left' => 'R$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Bahamian Dollar',
                'code' => 'BSD',
                'symbol_left' => '$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Pula',
                'code' => 'BWP',
                'symbol_left' => 'P',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Belarussian Ruble',
                'code' => 'BYR',
                'symbol_left' => '₽',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Belize Dollar',
                'code' => 'BZD',
                'symbol_left' => 'BZ$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Canadian Dollar',
                'code' => 'CAD',
                'symbol_left' => '$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'Swiss Franc',
                'code' => 'CHF',
                'symbol_left' => 'CHF',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'CLF Chilean Peso Unidades de fomento',
                'code' => 'CLP',
                'symbol_left' => '$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'title' => 'Yuan Renminbi',
                'code' => 'CNY',
                'symbol_left' => '¥',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'title' => 'COU Colombian Peso Unidad de Valor Real',
                'code' => 'COP',
                'symbol_left' => '$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'title' => 'Costa Rican Colon',
                'code' => 'CRC',
                'symbol_left' => '₡',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'title' => 'CUC Cuban Peso Peso Convertible',
                'code' => 'CUP',
                'symbol_left' => '₱',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'title' => 'Czech Koruna',
                'code' => 'CZK',
                'symbol_left' => 'Kč',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'title' => 'Danish Krone',
                'code' => 'DKK',
                'symbol_left' => 'kr',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'title' => 'Dominican Peso',
                'code' => 'DOP',
                'symbol_left' => 'RD$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'title' => 'Egyptian Pound',
                'code' => 'EGP',
                'symbol_left' => '£',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'Euro',
                'code' => 'EUR',
                'symbol_left' => '€',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'title' => 'Fiji Dollar',
                'code' => 'FJD',
                'symbol_left' => '$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'title' => 'Falkland Islands Pound',
                'code' => 'FKP',
                'symbol_left' => '£',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'title' => 'Pound Sterling',
                'code' => 'GBP',
                'symbol_left' => '£',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'title' => 'Gibraltar Pound',
                'code' => 'GIP',
                'symbol_left' => '£',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'title' => 'Quetzal',
                'code' => 'GTQ',
                'symbol_left' => 'Q',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'title' => 'Guyana Dollar',
                'code' => 'GYD',
                'symbol_left' => '$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'title' => 'Hong Kong Dollar',
                'code' => 'HKD',
                'symbol_left' => '$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'title' => 'Lempira',
                'code' => 'HNL',
                'symbol_left' => 'L',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'title' => 'Croatian Kuna',
                'code' => 'HRK',
                'symbol_left' => 'kn',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'title' => 'Forint',
                'code' => 'HUF',
                'symbol_left' => 'Ft',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'title' => 'Rupiah',
                'code' => 'IDR',
                'symbol_left' => 'Rp',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'title' => 'New Israeli Sheqel',
                'code' => 'ILS',
                'symbol_left' => '₪',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'title' => 'Iranian Rial',
                'code' => 'IRR',
                'symbol_left' => '﷼',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'title' => 'Iceland Krona',
                'code' => 'ISK',
                'symbol_left' => 'kr',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'title' => 'Jamaican Dollar',
                'code' => 'JMD',
                'symbol_left' => 'J$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'title' => 'Yen',
                'code' => 'JPY',
                'symbol_left' => '¥',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'title' => 'Som',
                'code' => 'KGS',
                'symbol_left' => 'лв',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'title' => 'Riel',
                'code' => 'KHR',
                'symbol_left' => '៛',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'title' => 'North Korean Won',
                'code' => 'KPW',
                'symbol_left' => '₩',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'title' => 'Won',
                'code' => 'KRW',
                'symbol_left' => '₩',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'title' => 'Cayman Islands Dollar',
                'code' => 'KYD',
                'symbol_left' => '$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'title' => 'Tenge',
                'code' => 'KZT',
                'symbol_left' => 'лв',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'title' => 'Kip',
                'code' => 'LAK',
                'symbol_left' => '₭',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'title' => 'Lebanese Pound',
                'code' => 'LBP',
                'symbol_left' => '£',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'title' => 'Sri Lanka Rupee',
                'code' => 'LKR',
                'symbol_left' => '₨',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'title' => 'Liberian Dollar',
                'code' => 'LRD',
                'symbol_left' => '$',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'title' => 'Lithuanian Litas',
                'code' => 'LTL',
                'symbol_left' => 'Lt',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'title' => 'Latvian Lats',
                'code' => 'LVL',
                'symbol_left' => 'Ls',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'title' => 'Denar',
                'code' => 'MKD',
                'symbol_left' => 'ден',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'title' => 'Tugrik',
                'code' => 'MNT',
                'symbol_left' => '₮',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'title' => 'Mauritius Rupee',
                'code' => 'MUR',
                'symbol_left' => '₨',
                'symbol_right' => NULL,
                'decimal_place' => NULL,
                '15,8' => 1.0,
                'is_active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'title' => 'MXV Mexican Peso Mexican Unidad de Inversion (UDI]',
                    'code' => 'MXN',
                    'symbol_left' => '$',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                63 => 
                array (
                    'id' => 64,
                    'title' => 'Malaysian Ringgit',
                    'code' => 'MYR',
                    'symbol_left' => 'RM',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                64 => 
                array (
                    'id' => 65,
                    'title' => 'Metical',
                    'code' => 'MZN',
                    'symbol_left' => 'MT',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                65 => 
                array (
                    'id' => 66,
                    'title' => 'Naira',
                    'code' => 'NGN',
                    'symbol_left' => '₦',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                66 => 
                array (
                    'id' => 67,
                    'title' => 'Cordoba Oro',
                    'code' => 'NIO',
                    'symbol_left' => 'C$',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                67 => 
                array (
                    'id' => 68,
                    'title' => 'Norwegian Krone',
                    'code' => 'NOK',
                    'symbol_left' => 'kr',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                68 => 
                array (
                    'id' => 69,
                    'title' => 'Nepalese Rupee',
                    'code' => 'NPR',
                    'symbol_left' => '₨',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                69 => 
                array (
                    'id' => 70,
                    'title' => 'New Zealand Dollar',
                    'code' => 'NZD',
                    'symbol_left' => '$',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                70 => 
                array (
                    'id' => 71,
                    'title' => 'Rial Omani',
                    'code' => 'OMR',
                    'symbol_left' => '﷼',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                71 => 
                array (
                    'id' => 72,
                    'title' => 'USD Balboa US Dollar',
                    'code' => 'PAB',
                    'symbol_left' => 'B/.',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                72 => 
                array (
                    'id' => 73,
                    'title' => 'Nuevo Sol',
                    'code' => 'PEN',
                    'symbol_left' => 'S/.',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                73 => 
                array (
                    'id' => 74,
                    'title' => 'Philippine Peso',
                    'code' => 'PHP',
                    'symbol_left' => 'Php',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                74 => 
                array (
                    'id' => 75,
                    'title' => 'Pakistan Rupee',
                    'code' => 'PKR',
                    'symbol_left' => '₨',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                75 => 
                array (
                    'id' => 76,
                    'title' => 'Zloty',
                    'code' => 'PLN',
                    'symbol_left' => 'zł',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                76 => 
                array (
                    'id' => 77,
                    'title' => 'Guarani',
                    'code' => 'PYG',
                    'symbol_left' => 'Gs',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                77 => 
                array (
                    'id' => 78,
                    'title' => 'Qatari Rial',
                    'code' => 'QAR',
                    'symbol_left' => '﷼',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                78 => 
                array (
                    'id' => 79,
                    'title' => 'New Leu',
                    'code' => 'RON',
                    'symbol_left' => 'lei',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                79 => 
                array (
                    'id' => 80,
                    'title' => 'Serbian Dinar',
                    'code' => 'RSD',
                    'symbol_left' => 'Дин.',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                80 => 
                array (
                    'id' => 81,
                    'title' => 'Russian Ruble',
                    'code' => 'RUB',
                    'symbol_left' => 'руб',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                81 => 
                array (
                    'id' => 82,
                    'title' => 'Saudi Riyal',
                    'code' => 'SAR',
                    'symbol_left' => '﷼',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                82 => 
                array (
                    'id' => 83,
                    'title' => 'Solomon Islands Dollar',
                    'code' => 'SBD',
                    'symbol_left' => '$',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                83 => 
                array (
                    'id' => 84,
                    'title' => 'Seychelles Rupee',
                    'code' => 'SCR',
                    'symbol_left' => '₨',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                84 => 
                array (
                    'id' => 85,
                    'title' => 'Swedish Krona',
                    'code' => 'SEK',
                    'symbol_left' => 'kr',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                85 => 
                array (
                    'id' => 86,
                    'title' => 'Singapore Dollar',
                    'code' => 'SGD',
                    'symbol_left' => '$',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                86 => 
                array (
                    'id' => 87,
                    'title' => 'Saint Helena Pound',
                    'code' => 'SHP',
                    'symbol_left' => '£',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                87 => 
                array (
                    'id' => 88,
                    'title' => 'Somali Shilling',
                    'code' => 'SOS',
                    'symbol_left' => 'S',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                88 => 
                array (
                    'id' => 89,
                    'title' => 'Surinam Dollar',
                    'code' => 'SRD',
                    'symbol_left' => '$',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                89 => 
                array (
                    'id' => 90,
                    'title' => 'USD El Salvador Colon US Dollar',
                    'code' => 'SVC',
                    'symbol_left' => '$',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                90 => 
                array (
                    'id' => 91,
                    'title' => 'Syrian Pound',
                    'code' => 'SYP',
                    'symbol_left' => '£',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                91 => 
                array (
                    'id' => 92,
                    'title' => 'Baht',
                    'code' => 'THB',
                    'symbol_left' => '฿',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                92 => 
                array (
                    'id' => 93,
                    'title' => 'Turkish Lira',
                    'code' => 'TRY',
                    'symbol_left' => 'TL',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                93 => 
                array (
                    'id' => 94,
                    'title' => 'Trinidad and Tobago Dollar',
                    'code' => 'TTD',
                    'symbol_left' => 'TT$',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                94 => 
                array (
                    'id' => 95,
                    'title' => 'New Taiwan Dollar',
                    'code' => 'TWD',
                    'symbol_left' => 'NT$',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                95 => 
                array (
                    'id' => 96,
                    'title' => 'Hryvnia',
                    'code' => 'UAH',
                    'symbol_left' => '₴',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                96 => 
                array (
                    'id' => 97,
                    'title' => 'US Dollar',
                    'code' => 'USD',
                    'symbol_left' => '$',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                97 => 
                array (
                    'id' => 98,
                    'title' => 'UYI Uruguay Peso en Unidades Indexadas',
                    'code' => 'UYU',
                    'symbol_left' => '$U',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                98 => 
                array (
                    'id' => 99,
                    'title' => 'Uzbekistan Sum',
                    'code' => 'UZS',
                    'symbol_left' => 'лв',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                99 => 
                array (
                    'id' => 100,
                    'title' => 'Bolivar Fuerte',
                    'code' => 'VEF',
                    'symbol_left' => 'Bs',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                100 => 
                array (
                    'id' => 101,
                    'title' => 'Dong',
                    'code' => 'VND',
                    'symbol_left' => '₫',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                101 => 
                array (
                    'id' => 102,
                    'title' => 'East Caribbean Dollar',
                    'code' => 'XCD',
                    'symbol_left' => '$',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                102 => 
                array (
                    'id' => 103,
                    'title' => 'Yemeni Rial',
                    'code' => 'YER',
                    'symbol_left' => '﷼',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                103 => 
                array (
                    'id' => 104,
                    'title' => 'Rand',
                    'code' => 'ZAR',
                    'symbol_left' => 'R',
                    'symbol_right' => NULL,
                    'decimal_place' => NULL,
                    '15,8' => 1.0,
                    'is_active' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            ));
        
        
    }
}