<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(array (
            0 => 
            array (
                'id' => 1,
                'customer_id' => 43,
                'total' => '180.00',
                'status' => 'received',
                'store_id' => 2,
                'payment_gateway_id' => 2,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => NULL,
                'cart_id' => 79,
                'sub_total' => '180.00',
                'shipping_weight' => '0.00',
                'created_at' => '2020-10-29 08:04:17',
                'updated_at' => '2020-10-29 08:24:58',
                'deleted_at' => NULL,
                'order_id' => NULL,
                'shipping_gateway_id' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'customer_id' => 43,
                'total' => '35.00',
                'status' => 'received',
                'store_id' => 2,
                'payment_gateway_id' => 2,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => NULL,
                'cart_id' => 81,
                'sub_total' => '35.00',
                'shipping_weight' => '0.00',
                'created_at' => '2020-10-29 17:52:25',
                'updated_at' => '2020-10-29 17:52:25',
                'deleted_at' => NULL,
                'order_id' => NULL,
                'shipping_gateway_id' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'customer_id' => 44,
                'total' => '250.00',
                'status' => 'received',
                'store_id' => 2,
                'payment_gateway_id' => 2,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => NULL,
                'cart_id' => 83,
                'sub_total' => '250.00',
                'shipping_weight' => '0.00',
                'created_at' => '2020-10-29 23:54:35',
                'updated_at' => '2020-10-29 23:54:35',
                'deleted_at' => NULL,
                'order_id' => NULL,
                'shipping_gateway_id' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'customer_id' => 44,
                'total' => '63.00',
                'status' => 'received',
                'store_id' => 2,
                'payment_gateway_id' => 2,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => NULL,
                'cart_id' => 84,
                'sub_total' => '63.00',
                'shipping_weight' => '0.00',
                'created_at' => '2020-10-29 23:55:45',
                'updated_at' => '2020-10-29 23:55:45',
                'deleted_at' => NULL,
                'order_id' => NULL,
                'shipping_gateway_id' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'customer_id' => 44,
                'total' => '63.00',
                'status' => 'received',
                'store_id' => 2,
                'payment_gateway_id' => 2,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => NULL,
                'cart_id' => 85,
                'sub_total' => '63.00',
                'shipping_weight' => '0.00',
                'created_at' => '2020-10-30 00:24:52',
                'updated_at' => '2020-10-30 00:34:53',
                'deleted_at' => NULL,
                'order_id' => NULL,
                'shipping_gateway_id' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'customer_id' => 39,
                'total' => '39.00',
                'status' => 'received',
                'store_id' => 2,
                'payment_gateway_id' => 2,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => NULL,
                'cart_id' => 88,
                'sub_total' => '39.00',
                'shipping_weight' => '0.00',
                'created_at' => '2020-10-30 17:53:20',
                'updated_at' => '2020-10-30 17:53:20',
                'deleted_at' => NULL,
                'order_id' => NULL,
                'shipping_gateway_id' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'customer_id' => 66,
                'total' => '75.00',
                'status' => 'received',
                'store_id' => 2,
                'payment_gateway_id' => 2,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => NULL,
                'cart_id' => 94,
                'sub_total' => '75.00',
                'shipping_weight' => '0.00',
                'created_at' => '2020-10-31 22:00:34',
                'updated_at' => '2020-10-31 22:00:34',
                'deleted_at' => NULL,
                'order_id' => NULL,
                'shipping_gateway_id' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'customer_id' => 39,
                'total' => '48.00',
                'status' => 'received',
                'store_id' => 2,
                'payment_gateway_id' => 2,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => NULL,
                'cart_id' => 96,
                'sub_total' => '48.00',
                'shipping_weight' => '0.00',
                'created_at' => '2020-11-03 01:58:21',
                'updated_at' => '2020-11-03 01:58:21',
                'deleted_at' => NULL,
                'order_id' => NULL,
                'shipping_gateway_id' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'customer_id' => 66,
                'total' => '140.00',
                'status' => 'received',
                'store_id' => 2,
                'payment_gateway_id' => 1,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => NULL,
                'cart_id' => 99,
                'sub_total' => '140.00',
                'shipping_weight' => '0.00',
                'created_at' => '2020-11-29 00:47:07',
                'updated_at' => '2020-11-29 00:47:07',
                'deleted_at' => NULL,
                'order_id' => NULL,
                'shipping_gateway_id' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'customer_id' => 66,
                'total' => '152.00',
                'status' => 'received',
                'store_id' => 2,
                'payment_gateway_id' => 1,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => NULL,
                'cart_id' => 103,
                'sub_total' => '152.00',
                'shipping_weight' => '0.00',
                'created_at' => '2020-11-29 10:23:08',
                'updated_at' => '2020-11-29 10:23:08',
                'deleted_at' => NULL,
                'order_id' => NULL,
                'shipping_gateway_id' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'customer_id' => 66,
                'total' => '48.00',
                'status' => 'received',
                'store_id' => 2,
                'payment_gateway_id' => 1,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => NULL,
                'cart_id' => 107,
                'sub_total' => '48.00',
                'shipping_weight' => '0.00',
                'created_at' => '2020-11-30 20:00:22',
                'updated_at' => '2020-11-30 20:00:22',
                'deleted_at' => NULL,
                'order_id' => NULL,
                'shipping_gateway_id' => NULL,
            ),
            11 => 
            array (
                'id' => 113,
                'customer_id' => 80,
                'total' => '3233.75',
                'status' => 'refunded',
                'store_id' => 2,
                'payment_gateway_id' => 2,
                'sales_tax' => '91.25',
                'shipping_cost' => '1500.00',
                'discount_cost' => '182.50',
                'cart_id' => 287,
                'sub_total' => '1825.00',
                'shipping_weight' => '14.35',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH428895',
                'shipping_gateway_id' => 3,
            ),
            12 => 
            array (
                'id' => 114,
                'customer_id' => 23,
                'total' => '20839.00',
                'status' => 'cancelled',
                'store_id' => 2,
                'payment_gateway_id' => 3,
                'sales_tax' => '0.00',
                'shipping_cost' => '1500.00',
                'discount_cost' => '0.00',
                'cart_id' => 288,
                'sub_total' => '19339.00',
                'shipping_weight' => '16.04',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH273341',
                'shipping_gateway_id' => 3,
            ),
            13 => 
            array (
                'id' => 115,
                'customer_id' => 80,
                'total' => '15135.00',
                'status' => 'cancelled',
                'store_id' => 2,
                'payment_gateway_id' => 2,
                'sales_tax' => '0.00',
                'shipping_cost' => '1500.00',
                'discount_cost' => '1515.00',
                'cart_id' => 289,
                'sub_total' => '15150.00',
                'shipping_weight' => '17.33',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH036195',
                'shipping_gateway_id' => 1,
            ),
            14 => 
            array (
                'id' => 116,
                'customer_id' => 10,
                'total' => '19460.70',
                'status' => 'fulfilled',
                'store_id' => 2,
                'payment_gateway_id' => 3,
                'sales_tax' => '945.30',
                'shipping_cost' => '1500.00',
                'discount_cost' => '1890.60',
                'cart_id' => 290,
                'sub_total' => '18906.00',
                'shipping_weight' => '4.97',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH872664',
                'shipping_gateway_id' => 3,
            ),
            15 => 
            array (
                'id' => 117,
                'customer_id' => 66,
                'total' => '12455.00',
                'status' => 'returned',
                'store_id' => 2,
                'payment_gateway_id' => 6,
                'sales_tax' => '0.00',
                'shipping_cost' => '1500.00',
                'discount_cost' => '0.00',
                'cart_id' => 291,
                'sub_total' => '10955.00',
                'shipping_weight' => '1.20',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH106746',
                'shipping_gateway_id' => 1,
            ),
            16 => 
            array (
                'id' => 118,
                'customer_id' => 80,
                'total' => '14699.70',
                'status' => 'refunded',
                'store_id' => 2,
                'payment_gateway_id' => 2,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => '1633.30',
                'cart_id' => 292,
                'sub_total' => '16333.00',
                'shipping_weight' => '20.51',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH899817',
                'shipping_gateway_id' => 4,
            ),
            17 => 
            array (
                'id' => 119,
                'customer_id' => 3,
                'total' => '5730.00',
                'status' => 'delivered',
                'store_id' => 2,
                'payment_gateway_id' => 5,
                'sales_tax' => '0.00',
                'shipping_cost' => '1500.00',
                'discount_cost' => '0.00',
                'cart_id' => 293,
                'sub_total' => '4230.00',
                'shipping_weight' => '6.78',
                'created_at' => '2021-06-30 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH327756',
                'shipping_gateway_id' => 4,
            ),
            18 => 
            array (
                'id' => 120,
                'customer_id' => 95,
                'total' => '15229.00',
                'status' => 'returned',
                'store_id' => 2,
                'payment_gateway_id' => 5,
                'sales_tax' => '0.00',
                'shipping_cost' => '1500.00',
                'discount_cost' => '0.00',
                'cart_id' => 294,
                'sub_total' => '13729.00',
                'shipping_weight' => '24.59',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH444161',
                'shipping_gateway_id' => 4,
            ),
            19 => 
            array (
                'id' => 121,
                'customer_id' => 14,
                'total' => '2813.90',
                'status' => 'returned',
                'store_id' => 2,
                'payment_gateway_id' => 7,
                'sales_tax' => '148.10',
                'shipping_cost' => '0.00',
                'discount_cost' => '296.20',
                'cart_id' => 295,
                'sub_total' => '2962.00',
                'shipping_weight' => '21.59',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH375991',
                'shipping_gateway_id' => 3,
            ),
            20 => 
            array (
                'id' => 122,
                'customer_id' => 40,
                'total' => '4058.00',
                'status' => 'confirmed',
                'store_id' => 2,
                'payment_gateway_id' => 3,
                'sales_tax' => '0.00',
                'shipping_cost' => '1500.00',
                'discount_cost' => '0.00',
                'cart_id' => 296,
                'sub_total' => '2558.00',
                'shipping_weight' => '13.63',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH038661',
                'shipping_gateway_id' => 4,
            ),
            21 => 
            array (
                'id' => 123,
                'customer_id' => 73,
                'total' => '12407.40',
                'status' => 'pending',
                'store_id' => 2,
                'payment_gateway_id' => 4,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => '1378.60',
                'cart_id' => 297,
                'sub_total' => '13786.00',
                'shipping_weight' => '11.19',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH457205',
                'shipping_gateway_id' => 3,
            ),
            22 => 
            array (
                'id' => 124,
                'customer_id' => 19,
                'total' => '21276.75',
                'status' => 'confirmed',
                'store_id' => 2,
                'payment_gateway_id' => 3,
                'sales_tax' => '941.75',
                'shipping_cost' => '1500.00',
                'discount_cost' => '0.00',
                'cart_id' => 298,
                'sub_total' => '18835.00',
                'shipping_weight' => '10.19',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH848899',
                'shipping_gateway_id' => 1,
            ),
            23 => 
            array (
                'id' => 125,
                'customer_id' => 28,
                'total' => '18017.00',
                'status' => 'fulfilled',
                'store_id' => 2,
                'payment_gateway_id' => 4,
                'sales_tax' => '0.00',
                'shipping_cost' => '1500.00',
                'discount_cost' => '0.00',
                'cart_id' => 299,
                'sub_total' => '16517.00',
                'shipping_weight' => '8.02',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH481416',
                'shipping_gateway_id' => 1,
            ),
            24 => 
            array (
                'id' => 126,
                'customer_id' => 12,
                'total' => '11427.75',
                'status' => 'confirmed',
                'store_id' => 2,
                'payment_gateway_id' => 6,
                'sales_tax' => '472.75',
                'shipping_cost' => '1500.00',
                'discount_cost' => '0.00',
                'cart_id' => 300,
                'sub_total' => '9455.00',
                'shipping_weight' => '20.58',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH705324',
                'shipping_gateway_id' => 4,
            ),
            25 => 
            array (
                'id' => 127,
                'customer_id' => 75,
                'total' => '17748.00',
                'status' => 'fulfilled',
                'store_id' => 2,
                'payment_gateway_id' => 3,
                'sales_tax' => '0.00',
                'shipping_cost' => '1500.00',
                'discount_cost' => '0.00',
                'cart_id' => 301,
                'sub_total' => '16248.00',
                'shipping_weight' => '14.95',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH362124',
                'shipping_gateway_id' => 1,
            ),
            26 => 
            array (
                'id' => 128,
                'customer_id' => 70,
                'total' => '3250.80',
                'status' => 'cancelled',
                'store_id' => 2,
                'payment_gateway_id' => 3,
                'sales_tax' => '154.80',
                'shipping_cost' => '0.00',
                'discount_cost' => '0.00',
                'cart_id' => 302,
                'sub_total' => '3096.00',
                'shipping_weight' => '28.39',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH159138',
                'shipping_gateway_id' => 2,
            ),
            27 => 
            array (
                'id' => 129,
                'customer_id' => 20,
                'total' => '14781.00',
                'status' => 'fulfilled',
                'store_id' => 2,
                'payment_gateway_id' => 6,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => '0.00',
                'cart_id' => 303,
                'sub_total' => '14781.00',
                'shipping_weight' => '3.80',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH081895',
                'shipping_gateway_id' => 2,
            ),
            28 => 
            array (
                'id' => 130,
                'customer_id' => 74,
                'total' => '14786.70',
                'status' => 'cancelled',
                'store_id' => 2,
                'payment_gateway_id' => 3,
                'sales_tax' => '0.00',
                'shipping_cost' => '1500.00',
                'discount_cost' => '1476.30',
                'cart_id' => 304,
                'sub_total' => '14763.00',
                'shipping_weight' => '22.82',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH990021',
                'shipping_gateway_id' => 2,
            ),
            29 => 
            array (
                'id' => 131,
                'customer_id' => 35,
                'total' => '11744.85',
                'status' => 'pending',
                'store_id' => 2,
                'payment_gateway_id' => 7,
                'sales_tax' => '487.85',
                'shipping_cost' => '1500.00',
                'discount_cost' => '0.00',
                'cart_id' => 305,
                'sub_total' => '9757.00',
                'shipping_weight' => '28.29',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH582088',
                'shipping_gateway_id' => 2,
            ),
            30 => 
            array (
                'id' => 132,
                'customer_id' => 7,
                'total' => '14906.00',
                'status' => 'confirmed',
                'store_id' => 2,
                'payment_gateway_id' => 6,
                'sales_tax' => '0.00',
                'shipping_cost' => '1500.00',
                'discount_cost' => '0.00',
                'cart_id' => 306,
                'sub_total' => '13406.00',
                'shipping_weight' => '27.30',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH300639',
                'shipping_gateway_id' => 1,
            ),
            31 => 
            array (
                'id' => 133,
                'customer_id' => 25,
                'total' => '6792.50',
                'status' => 'delivered',
                'store_id' => 2,
                'payment_gateway_id' => 6,
                'sales_tax' => '357.50',
                'shipping_cost' => '0.00',
                'discount_cost' => '715.00',
                'cart_id' => 307,
                'sub_total' => '7150.00',
                'shipping_weight' => '26.33',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH367059',
                'shipping_gateway_id' => 2,
            ),
            32 => 
            array (
                'id' => 134,
                'customer_id' => 26,
                'total' => '9071.10',
                'status' => 'confirmed',
                'store_id' => 2,
                'payment_gateway_id' => 5,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => '1007.90',
                'cart_id' => 308,
                'sub_total' => '10079.00',
                'shipping_weight' => '23.65',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH477077',
                'shipping_gateway_id' => 3,
            ),
            33 => 
            array (
                'id' => 135,
                'customer_id' => 35,
                'total' => '16690.80',
                'status' => 'fulfilled',
                'store_id' => 2,
                'payment_gateway_id' => 7,
                'sales_tax' => '794.80',
                'shipping_cost' => '0.00',
                'discount_cost' => '0.00',
                'cart_id' => 309,
                'sub_total' => '15896.00',
                'shipping_weight' => '10.11',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH140013',
                'shipping_gateway_id' => 4,
            ),
            34 => 
            array (
                'id' => 136,
                'customer_id' => 86,
                'total' => '4500.10',
                'status' => 'cancelled',
                'store_id' => 2,
                'payment_gateway_id' => 3,
                'sales_tax' => '157.90',
                'shipping_cost' => '1500.00',
                'discount_cost' => '315.80',
                'cart_id' => 310,
                'sub_total' => '3158.00',
                'shipping_weight' => '11.84',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH115769',
                'shipping_gateway_id' => 1,
            ),
            35 => 
            array (
                'id' => 137,
                'customer_id' => 38,
                'total' => '7309.05',
                'status' => 'refunded',
                'store_id' => 2,
                'payment_gateway_id' => 5,
                'sales_tax' => '348.05',
                'shipping_cost' => '0.00',
                'discount_cost' => '0.00',
                'cart_id' => 311,
                'sub_total' => '6961.00',
                'shipping_weight' => '5.62',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH756479',
                'shipping_gateway_id' => 2,
            ),
            36 => 
            array (
                'id' => 138,
                'customer_id' => 28,
                'total' => '11176.00',
                'status' => 'pending',
                'store_id' => 2,
                'payment_gateway_id' => 2,
                'sales_tax' => '0.00',
                'shipping_cost' => '1500.00',
                'discount_cost' => '0.00',
                'cart_id' => 312,
                'sub_total' => '9676.00',
                'shipping_weight' => '19.84',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH742233',
                'shipping_gateway_id' => 1,
            ),
            37 => 
            array (
                'id' => 139,
                'customer_id' => 10,
                'total' => '7431.90',
                'status' => 'shipped',
                'store_id' => 2,
                'payment_gateway_id' => 7,
                'sales_tax' => '353.90',
                'shipping_cost' => '0.00',
                'discount_cost' => '0.00',
                'cart_id' => 313,
                'sub_total' => '7078.00',
                'shipping_weight' => '15.09',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH176127',
                'shipping_gateway_id' => 2,
            ),
            38 => 
            array (
                'id' => 140,
                'customer_id' => 49,
                'total' => '1397.70',
                'status' => 'returned',
                'store_id' => 2,
                'payment_gateway_id' => 3,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => '155.30',
                'cart_id' => 314,
                'sub_total' => '1553.00',
                'shipping_weight' => '14.10',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH700584',
                'shipping_gateway_id' => 3,
            ),
            39 => 
            array (
                'id' => 141,
                'customer_id' => 16,
                'total' => '19743.15',
                'status' => 'returned',
                'store_id' => 2,
                'payment_gateway_id' => 3,
                'sales_tax' => '940.15',
                'shipping_cost' => '0.00',
                'discount_cost' => '0.00',
                'cart_id' => 315,
                'sub_total' => '18803.00',
                'shipping_weight' => '15.38',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH858884',
                'shipping_gateway_id' => 2,
            ),
            40 => 
            array (
                'id' => 142,
                'customer_id' => 8,
                'total' => '14240.70',
                'status' => 'refunded',
                'store_id' => 2,
                'payment_gateway_id' => 4,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => '1582.30',
                'cart_id' => 316,
                'sub_total' => '15823.00',
                'shipping_weight' => '16.77',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH721968',
                'shipping_gateway_id' => 4,
            ),
            41 => 
            array (
                'id' => 143,
                'customer_id' => 49,
                'total' => '20899.20',
                'status' => 'fulfilled',
                'store_id' => 2,
                'payment_gateway_id' => 5,
                'sales_tax' => '995.20',
                'shipping_cost' => '0.00',
                'discount_cost' => '0.00',
                'cart_id' => 317,
                'sub_total' => '19904.00',
                'shipping_weight' => '7.82',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH507302',
                'shipping_gateway_id' => 3,
            ),
            42 => 
            array (
                'id' => 144,
                'customer_id' => 46,
                'total' => '3427.00',
                'status' => 'delivered',
                'store_id' => 2,
                'payment_gateway_id' => 4,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => '0.00',
                'cart_id' => 318,
                'sub_total' => '3427.00',
                'shipping_weight' => '19.66',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH482686',
                'shipping_gateway_id' => 3,
            ),
            43 => 
            array (
                'id' => 145,
                'customer_id' => 88,
                'total' => '7453.65',
                'status' => 'pending',
                'store_id' => 2,
                'payment_gateway_id' => 3,
                'sales_tax' => '313.35',
                'shipping_cost' => '1500.00',
                'discount_cost' => '626.70',
                'cart_id' => 319,
                'sub_total' => '6267.00',
                'shipping_weight' => '4.62',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH380866',
                'shipping_gateway_id' => 2,
            ),
            44 => 
            array (
                'id' => 146,
                'customer_id' => 54,
                'total' => '10324.00',
                'status' => 'confirmed',
                'store_id' => 2,
                'payment_gateway_id' => 6,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => '0.00',
                'cart_id' => 320,
                'sub_total' => '10324.00',
                'shipping_weight' => '22.06',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH647254',
                'shipping_gateway_id' => 1,
            ),
            45 => 
            array (
                'id' => 147,
                'customer_id' => 3,
                'total' => '13645.00',
                'status' => 'pending',
                'store_id' => 2,
                'payment_gateway_id' => 4,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => '0.00',
                'cart_id' => 321,
                'sub_total' => '13645.00',
                'shipping_weight' => '3.81',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH796329',
                'shipping_gateway_id' => 3,
            ),
            46 => 
            array (
                'id' => 148,
                'customer_id' => 24,
                'total' => '14891.10',
                'status' => 'returned',
                'store_id' => 2,
                'payment_gateway_id' => 6,
                'sales_tax' => '709.10',
                'shipping_cost' => '0.00',
                'discount_cost' => '0.00',
                'cart_id' => 322,
                'sub_total' => '14182.00',
                'shipping_weight' => '18.34',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH031924',
                'shipping_gateway_id' => 3,
            ),
            47 => 
            array (
                'id' => 149,
                'customer_id' => 30,
                'total' => '16499.60',
                'status' => 'confirmed',
                'store_id' => 2,
                'payment_gateway_id' => 5,
                'sales_tax' => '868.40',
                'shipping_cost' => '0.00',
                'discount_cost' => '1736.80',
                'cart_id' => 323,
                'sub_total' => '17368.00',
                'shipping_weight' => '12.42',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH933890',
                'shipping_gateway_id' => 2,
            ),
            48 => 
            array (
                'id' => 150,
                'customer_id' => 40,
                'total' => '2429.15',
                'status' => 'fulfilled',
                'store_id' => 2,
                'payment_gateway_id' => 1,
                'sales_tax' => '127.85',
                'shipping_cost' => '0.00',
                'discount_cost' => '255.70',
                'cart_id' => 324,
                'sub_total' => '2557.00',
                'shipping_weight' => '8.22',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH548007',
                'shipping_gateway_id' => 4,
            ),
            49 => 
            array (
                'id' => 151,
                'customer_id' => 26,
                'total' => '4186.80',
                'status' => 'pending',
                'store_id' => 2,
                'payment_gateway_id' => 5,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => '465.20',
                'cart_id' => 325,
                'sub_total' => '4652.00',
                'shipping_weight' => '23.87',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH203316',
                'shipping_gateway_id' => 4,
            ),
            50 => 
            array (
                'id' => 152,
                'customer_id' => 43,
                'total' => '6151.20',
                'status' => 'delivered',
                'store_id' => 2,
                'payment_gateway_id' => 7,
                'sales_tax' => '244.80',
                'shipping_cost' => '1500.00',
                'discount_cost' => '489.60',
                'cart_id' => 326,
                'sub_total' => '4896.00',
                'shipping_weight' => '24.65',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH195857',
                'shipping_gateway_id' => 3,
            ),
            51 => 
            array (
                'id' => 153,
                'customer_id' => 24,
                'total' => '8588.55',
                'status' => 'shipped',
                'store_id' => 2,
                'payment_gateway_id' => 5,
                'sales_tax' => '337.55',
                'shipping_cost' => '1500.00',
                'discount_cost' => '0.00',
                'cart_id' => 327,
                'sub_total' => '6751.00',
                'shipping_weight' => '13.75',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH877169',
                'shipping_gateway_id' => 2,
            ),
            52 => 
            array (
                'id' => 154,
                'customer_id' => 16,
                'total' => '2060.10',
                'status' => 'pending',
                'store_id' => 2,
                'payment_gateway_id' => 5,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => '228.90',
                'cart_id' => 328,
                'sub_total' => '2289.00',
                'shipping_weight' => '29.55',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH850817',
                'shipping_gateway_id' => 2,
            ),
            53 => 
            array (
                'id' => 155,
                'customer_id' => 44,
                'total' => '9482.85',
                'status' => 'fulfilled',
                'store_id' => 2,
                'payment_gateway_id' => 3,
                'sales_tax' => '420.15',
                'shipping_cost' => '1500.00',
                'discount_cost' => '840.30',
                'cart_id' => 329,
                'sub_total' => '8403.00',
                'shipping_weight' => '1.22',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH412415',
                'shipping_gateway_id' => 2,
            ),
            54 => 
            array (
                'id' => 156,
                'customer_id' => 100,
                'total' => '12803.10',
                'status' => 'fulfilled',
                'store_id' => 2,
                'payment_gateway_id' => 2,
                'sales_tax' => '594.90',
                'shipping_cost' => '1500.00',
                'discount_cost' => '1189.80',
                'cart_id' => 330,
                'sub_total' => '11898.00',
                'shipping_weight' => '29.46',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH568863',
                'shipping_gateway_id' => 1,
            ),
            55 => 
            array (
                'id' => 157,
                'customer_id' => 24,
                'total' => '13004.00',
                'status' => 'shipped',
                'store_id' => 2,
                'payment_gateway_id' => 6,
                'sales_tax' => '0.00',
                'shipping_cost' => '1500.00',
                'discount_cost' => '0.00',
                'cart_id' => 331,
                'sub_total' => '11504.00',
                'shipping_weight' => '26.00',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH593658',
                'shipping_gateway_id' => 1,
            ),
            56 => 
            array (
                'id' => 158,
                'customer_id' => 58,
                'total' => '13681.80',
                'status' => 'confirmed',
                'store_id' => 2,
                'payment_gateway_id' => 5,
                'sales_tax' => '0.00',
                'shipping_cost' => '0.00',
                'discount_cost' => '1520.20',
                'cart_id' => 332,
                'sub_total' => '15202.00',
                'shipping_weight' => '16.27',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH652372',
                'shipping_gateway_id' => 4,
            ),
            57 => 
            array (
                'id' => 159,
                'customer_id' => 84,
                'total' => '18567.75',
                'status' => 'returned',
                'store_id' => 2,
                'payment_gateway_id' => 6,
                'sales_tax' => '977.25',
                'shipping_cost' => '0.00',
                'discount_cost' => '1954.50',
                'cart_id' => 333,
                'sub_total' => '19545.00',
                'shipping_weight' => '25.51',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH268307',
                'shipping_gateway_id' => 4,
            ),
            58 => 
            array (
                'id' => 160,
                'customer_id' => 23,
                'total' => '17719.00',
                'status' => 'shipped',
                'store_id' => 2,
                'payment_gateway_id' => 5,
                'sales_tax' => '0.00',
                'shipping_cost' => '1500.00',
                'discount_cost' => '0.00',
                'cart_id' => 334,
                'sub_total' => '16219.00',
                'shipping_weight' => '9.91',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH251242',
                'shipping_gateway_id' => 1,
            ),
            59 => 
            array (
                'id' => 161,
                'customer_id' => 57,
                'total' => '8327.70',
                'status' => 'fulfilled',
                'store_id' => 2,
                'payment_gateway_id' => 6,
                'sales_tax' => '438.30',
                'shipping_cost' => '0.00',
                'discount_cost' => '876.60',
                'cart_id' => 335,
                'sub_total' => '8766.00',
                'shipping_weight' => '5.77',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH821122',
                'shipping_gateway_id' => 3,
            ),
            60 => 
            array (
                'id' => 162,
                'customer_id' => 25,
                'total' => '9409.20',
                'status' => 'refunded',
                'store_id' => 2,
                'payment_gateway_id' => 7,
                'sales_tax' => '0.00',
                'shipping_cost' => '1500.00',
                'discount_cost' => '878.80',
                'cart_id' => 336,
                'sub_total' => '8788.00',
                'shipping_weight' => '24.62',
                'created_at' => '2021-10-31 11:25:35',
                'updated_at' => '2021-10-31 11:25:35',
                'deleted_at' => NULL,
                'order_id' => 'TBH241988',
                'shipping_gateway_id' => 3,
            ),
        ));
        
        
    }
}