<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TimezonesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('timezones')->delete();
        
        \DB::table('timezones')->insert(array (
            0 => 
            array (
                'id' => 1,
                'value' => 'DST',
                'offset' => -12,
                'isdst' => 0,
                'name' => 'Dateline Standard Time',
                'utc' => '["Etc\\/GMT+12","Etc\\/GMT+12"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-12:00) International Date Line West',
            ),
            1 => 
            array (
                'id' => 2,
                'value' => 'U',
                'offset' => -11,
                'isdst' => 0,
                'name' => 'UTC-11',
                'utc' => '["Etc\\/GMT+11","Pacific\\/Pago_Pago","Pacific\\/Niue","Pacific\\/Midway","Etc\\/GMT+11"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-11:00) Coordinated Universal Time-11',
            ),
            2 => 
            array (
                'id' => 3,
                'value' => 'HST',
                'offset' => -10,
                'isdst' => 0,
                'name' => 'Hawaiian Standard Time',
                'utc' => '["Pacific\\/Honolulu","Pacific\\/Rarotonga","Pacific\\/Tahiti","Pacific\\/Johnston","Pacific\\/Honolulu","Etc\\/GMT+10"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-10:00) Hawaii',
            ),
            3 => 
            array (
                'id' => 4,
                'value' => 'AKDT',
                'offset' => -8,
                'isdst' => 1,
                'name' => 'Alaskan Standard Time',
                'utc' => '["America\\/Anchorage","America\\/Anchorage America\\/Juneau America\\/Nome America\\/Sitka America\\/Yakutat"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-09:00) Alaska',
            ),
            4 => 
            array (
                'id' => 5,
                'value' => 'PDT',
                'offset' => -7,
                'isdst' => 1,
            'name' => 'Pacific Standard Time (Mexico)',
                'utc' => '["America\\/Santa_Isabel","America\\/Santa_Isabel"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-08:00) Baja California',
            ),
            5 => 
            array (
                'id' => 6,
                'value' => 'PDT',
                'offset' => -7,
                'isdst' => 1,
                'name' => 'Pacific Standard Time',
                'utc' => '["America\\/Los_Angeles","America\\/Vancouver America\\/Dawson America\\/Whitehorse","America\\/Tijuana","America\\/Los_Angeles","PST8PDT"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-08:00) Pacific Time (US & Canada)',
            ),
            6 => 
            array (
                'id' => 7,
                'value' => 'UMST',
                'offset' => -7,
                'isdst' => 0,
                'name' => 'US Mountain Standard Time',
                'utc' => '["America\\/Phoenix","America\\/Dawson_Creek America\\/Creston","America\\/Hermosillo","America\\/Phoenix","Etc\\/GMT+7"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-07:00) Arizona',
            ),
            7 => 
            array (
                'id' => 8,
                'value' => 'MDT',
                'offset' => -6,
                'isdst' => 1,
            'name' => 'Mountain Standard Time (Mexico)',
                'utc' => '["America\\/Chihuahua","America\\/Chihuahua America\\/Mazatlan"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
            ),
            8 => 
            array (
                'id' => 9,
                'value' => 'MDT',
                'offset' => -6,
                'isdst' => 1,
                'name' => 'Mountain Standard Time',
                'utc' => '["America\\/Denver","America\\/Edmonton America\\/Cambridge_Bay America\\/Inuvik America\\/Yellowknife","America\\/Ojinaga","America\\/Denver America\\/Boise","MST7MDT"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-07:00) Mountain Time (US & Canada)',
            ),
            9 => 
            array (
                'id' => 10,
                'value' => 'CAST',
                'offset' => -6,
                'isdst' => 0,
                'name' => 'Central America Standard Time',
                'utc' => '["America\\/Guatemala","America\\/Belize","America\\/Costa_Rica","Pacific\\/Galapagos","America\\/Guatemala","America\\/Tegucigalpa","America\\/Managua","America\\/El_Salvador","Etc\\/GMT+6"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-06:00) Central America',
            ),
            10 => 
            array (
                'id' => 11,
                'value' => 'CDT',
                'offset' => -5,
                'isdst' => 1,
                'name' => 'Central Standard Time',
                'utc' => '["America\\/Chicago","America\\/Winnipeg America\\/Rainy_River America\\/Rankin_Inlet America\\/Resolute","America\\/Matamoros","America\\/Chicago America\\/Indiana\\/Knox America\\/Indiana\\/Tell_City America\\/Menominee America\\/North_Dakota\\/Beulah America\\/North_Dakota\\/Center America\\/North_Dakota\\/New_Salem","CST6CDT"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-06:00) Central Time (US & Canada)',
            ),
            11 => 
            array (
                'id' => 12,
                'value' => 'CDT',
                'offset' => -5,
                'isdst' => 1,
            'name' => 'Central Standard Time (Mexico)',
                'utc' => '["America\\/Mexico_City","America\\/Mexico_City America\\/Bahia_Banderas America\\/Cancun America\\/Merida America\\/Monterrey"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-06:00) Guadalajara, Mexico City, Monterrey',
            ),
            12 => 
            array (
                'id' => 13,
                'value' => 'CCST',
                'offset' => -6,
                'isdst' => 0,
                'name' => 'Canada Central Standard Time',
                'utc' => '["America\\/Regina","America\\/Regina America\\/Swift_Current"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-06:00) Saskatchewan',
            ),
            13 => 
            array (
                'id' => 14,
                'value' => 'SPST',
                'offset' => -5,
                'isdst' => 0,
                'name' => 'SA Pacific Standard Time',
                'utc' => '["America\\/Bogota","America\\/Rio_Branco America\\/Eirunepe","America\\/Coral_Harbour","America\\/Bogota","America\\/Guayaquil","America\\/Jamaica","America\\/Cayman","America\\/Panama","America\\/Lima","Etc\\/GMT+5"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-05:00) Bogota, Lima, Quito',
            ),
            14 => 
            array (
                'id' => 15,
                'value' => 'EDT',
                'offset' => -4,
                'isdst' => 1,
                'name' => 'Eastern Standard Time',
                'utc' => '["America\\/New_York","America\\/Nassau","America\\/Toronto America\\/Iqaluit America\\/Montreal America\\/Nipigon America\\/Pangnirtung America\\/Thunder_Bay","America\\/Havana","America\\/Port-au-Prince","America\\/New_York America\\/Detroit America\\/Indiana\\/Petersburg America\\/Indiana\\/Vincennes America\\/Indiana\\/Winamac America\\/Kentucky\\/Monticello America\\/Louisville","EST5EDT"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-05:00) Eastern Time (US & Canada)',
            ),
            15 => 
            array (
                'id' => 16,
                'value' => 'UEDT',
                'offset' => -4,
                'isdst' => 1,
                'name' => 'US Eastern Standard Time',
                'utc' => '["America\\/Indianapolis","America\\/Indianapolis America\\/Indiana\\/Marengo America\\/Indiana\\/Vevay"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-05:00) Indiana (East)',
            ),
            16 => 
            array (
                'id' => 17,
                'value' => 'VST',
                'offset' => -5,
                'isdst' => 0,
                'name' => 'Venezuela Standard Time',
                'utc' => '["America\\/Caracas","America\\/Caracas"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-04:30) Caracas',
            ),
            17 => 
            array (
                'id' => 18,
                'value' => 'PST',
                'offset' => -4,
                'isdst' => 0,
                'name' => 'Paraguay Standard Time',
                'utc' => '["America\\/Asuncion","America\\/Asuncion"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-04:00) Asuncion',
            ),
            18 => 
            array (
                'id' => 19,
                'value' => 'ADT',
                'offset' => -3,
                'isdst' => 1,
                'name' => 'Atlantic Standard Time',
                'utc' => '["America\\/Halifax","Atlantic\\/Bermuda","America\\/Halifax America\\/Glace_Bay America\\/Goose_Bay America\\/Moncton","America\\/Thule"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-04:00) Atlantic Time (Canada)',
            ),
            19 => 
            array (
                'id' => 20,
                'value' => 'CBST',
                'offset' => -4,
                'isdst' => 0,
                'name' => 'Central Brazilian Standard Time',
                'utc' => '["America\\/Cuiaba","America\\/Cuiaba America\\/Campo_Grande"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-04:00) Cuiaba',
            ),
            20 => 
            array (
                'id' => 21,
                'value' => 'SWST',
                'offset' => -4,
                'isdst' => 0,
                'name' => 'SA Western Standard Time',
                'utc' => '["America\\/La_Paz","America\\/Antigua","America\\/Anguilla","America\\/Aruba","America\\/Barbados","America\\/St_Barthelemy","America\\/La_Paz","America\\/Kralendijk","America\\/Manaus America\\/Boa_Vista America\\/Porto_Velho","America\\/Blanc-Sablon","America\\/Curacao","America\\/Dominica","America\\/Santo_Domingo","America\\/Grenada","America\\/Guadeloupe","America\\/Guyana","America\\/St_Kitts","America\\/St_Lucia","America\\/Marigot","America\\/Martinique","America\\/Montserrat","America\\/Puerto_Rico","America\\/Lower_Princes","America\\/Grand_Turk","America\\/Port_of_Spain","America\\/St_Vincent","America\\/Tortola","America\\/St_Thomas","Etc\\/GMT+4"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',
            ),
            21 => 
            array (
                'id' => 22,
                'value' => 'PSST',
                'offset' => -4,
                'isdst' => 0,
                'name' => 'Pacific SA Standard Time',
                'utc' => '["America\\/Santiago","Antarctica\\/Palmer","America\\/Santiago"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-04:00) Santiago',
            ),
            22 => 
            array (
                'id' => 23,
                'value' => 'NDT',
                'offset' => -3,
                'isdst' => 1,
                'name' => 'Newfoundland Standard Time',
                'utc' => '["America\\/St_Johns","America\\/St_Johns"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-03:30) Newfoundland',
            ),
            23 => 
            array (
                'id' => 24,
                'value' => 'ESAST',
                'offset' => -3,
                'isdst' => 0,
                'name' => 'E. South America Standard Time',
                'utc' => '["America\\/Sao_Paulo","America\\/Sao_Paulo"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-03:00) Brasilia',
            ),
            24 => 
            array (
                'id' => 25,
                'value' => 'AST',
                'offset' => -3,
                'isdst' => 0,
                'name' => 'Argentina Standard Time',
                'utc' => '["America\\/Buenos_Aires","America\\/Buenos_Aires America\\/Argentina\\/La_Rioja America\\/Argentina\\/Rio_Gallegos America\\/Argentina\\/Salta America\\/Argentina\\/San_Juan America\\/Argentina\\/San_Luis America\\/Argentina\\/Tucuman America\\/Argentina\\/Ushuaia America\\/Catamarca America\\/Cordoba America\\/Jujuy America\\/Mendoza"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-03:00) Buenos Aires',
            ),
            25 => 
            array (
                'id' => 26,
                'value' => 'SEST',
                'offset' => -3,
                'isdst' => 0,
                'name' => 'SA Eastern Standard Time',
                'utc' => '["America\\/Cayenne","Antarctica\\/Rothera","America\\/Fortaleza America\\/Araguaina America\\/Belem America\\/Maceio America\\/Recife America\\/Santarem","Atlantic\\/Stanley","America\\/Cayenne","America\\/Paramaribo","Etc\\/GMT+3"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-03:00) Cayenne, Fortaleza',
            ),
            26 => 
            array (
                'id' => 27,
                'value' => 'GDT',
                'offset' => -2,
                'isdst' => 1,
                'name' => 'Greenland Standard Time',
                'utc' => '["America\\/Godthab","America\\/Godthab"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-03:00) Greenland',
            ),
            27 => 
            array (
                'id' => 28,
                'value' => 'MST',
                'offset' => -3,
                'isdst' => 0,
                'name' => 'Montevideo Standard Time',
                'utc' => '["America\\/Montevideo","America\\/Montevideo"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-03:00) Montevideo',
            ),
            28 => 
            array (
                'id' => 29,
                'value' => 'BST',
                'offset' => -3,
                'isdst' => 0,
                'name' => 'Bahia Standard Time',
                'utc' => '["America\\/Bahia","America\\/Bahia"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-03:00) Salvador',
            ),
            29 => 
            array (
                'id' => 30,
                'value' => 'U',
                'offset' => -2,
                'isdst' => 0,
                'name' => 'UTC-02',
                'utc' => '["Etc\\/GMT+2","America\\/Noronha","Atlantic\\/South_Georgia","Etc\\/GMT+2"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-02:00) Coordinated Universal Time-02',
            ),
            30 => 
            array (
                'id' => 31,
                'value' => 'MDT',
                'offset' => -1,
                'isdst' => 1,
                'name' => 'Mid-Atlantic Standard Time',
                'utc' => 'NULL',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-02:00) Mid-Atlantic - Old',
            ),
            31 => 
            array (
                'id' => 32,
                'value' => 'ADT',
                'offset' => 0,
                'isdst' => 1,
                'name' => 'Azores Standard Time',
                'utc' => '["Atlantic\\/Azores","America\\/Scoresbysund","Atlantic\\/Azores"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-01:00) Azores',
            ),
            32 => 
            array (
                'id' => 33,
                'value' => 'CVST',
                'offset' => -1,
                'isdst' => 0,
                'name' => 'Cape Verde Standard Time',
                'utc' => '["Atlantic\\/Cape_Verde","Atlantic\\/Cape_Verde","Etc\\/GMT+1"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC-01:00) Cape Verde Is.',
            ),
            33 => 
            array (
                'id' => 34,
                'value' => 'MDT',
                'offset' => 1,
                'isdst' => 1,
                'name' => 'Morocco Standard Time',
                'utc' => '["Africa\\/Casablanca","Africa\\/El_Aaiun","Africa\\/Casablanca"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC) Casablanca',
            ),
            34 => 
            array (
                'id' => 35,
                'value' => 'CUT',
                'offset' => 0,
                'isdst' => 0,
                'name' => 'UTC',
                'utc' => '["Etc\\/GMT","America\\/Danmarkshavn","Etc\\/GMT"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC) Coordinated Universal Time',
            ),
            35 => 
            array (
                'id' => 36,
                'value' => 'GDT',
                'offset' => 1,
                'isdst' => 1,
                'name' => 'GMT Standard Time',
                'utc' => '["Europe\\/London","Atlantic\\/Canary","Atlantic\\/Faeroe","Europe\\/London","Europe\\/Guernsey","Europe\\/Dublin","Europe\\/Isle_of_Man","Europe\\/Jersey","Europe\\/Lisbon Atlantic\\/Madeira"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC) Dublin, Edinburgh, Lisbon, London',
            ),
            36 => 
            array (
                'id' => 37,
                'value' => 'GST',
                'offset' => 0,
                'isdst' => 0,
                'name' => 'Greenwich Standard Time',
                'utc' => '["Atlantic\\/Reykjavik","Africa\\/Ouagadougou","Africa\\/Abidjan","Africa\\/Accra","Africa\\/Banjul","Africa\\/Conakry","Africa\\/Bissau","Atlantic\\/Reykjavik","Africa\\/Monrovia","Africa\\/Bamako","Africa\\/Nouakchott","Atlantic\\/St_Helena","Africa\\/Freetown","Africa\\/Dakar","Africa\\/Sao_Tome","Africa\\/Lome"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC) Monrovia, Reykjavik',
            ),
            37 => 
            array (
                'id' => 38,
                'value' => 'WEDT',
                'offset' => 2,
                'isdst' => 1,
                'name' => 'W. Europe Standard Time',
                'utc' => '["Europe\\/Berlin","Europe\\/Andorra","Europe\\/Vienna","Europe\\/Zurich","Europe\\/Berlin Europe\\/Busingen","Europe\\/Gibraltar","Europe\\/Rome","Europe\\/Vaduz","Europe\\/Luxembourg","Europe\\/Monaco","Europe\\/Malta","Europe\\/Amsterdam","Europe\\/Oslo","Europe\\/Stockholm","Arctic\\/Longyearbyen","Europe\\/San_Marino","Europe\\/Vatican"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
            ),
            38 => 
            array (
                'id' => 39,
                'value' => 'CEDT',
                'offset' => 2,
                'isdst' => 1,
                'name' => 'Central Europe Standard Time',
                'utc' => '["Europe\\/Budapest","Europe\\/Tirane","Europe\\/Prague","Europe\\/Budapest","Europe\\/Podgorica","Europe\\/Belgrade","Europe\\/Ljubljana","Europe\\/Bratislava"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
            ),
            39 => 
            array (
                'id' => 40,
                'value' => 'RDT',
                'offset' => 2,
                'isdst' => 1,
                'name' => 'Romance Standard Time',
                'utc' => '["Europe\\/Paris","Europe\\/Brussels","Europe\\/Copenhagen","Europe\\/Madrid Africa\\/Ceuta","Europe\\/Paris"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
            ),
            40 => 
            array (
                'id' => 41,
                'value' => 'CEDT',
                'offset' => 2,
                'isdst' => 1,
                'name' => 'Central European Standard Time',
                'utc' => '["Europe\\/Warsaw","Europe\\/Sarajevo","Europe\\/Zagreb","Europe\\/Skopje","Europe\\/Warsaw"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
            ),
            41 => 
            array (
                'id' => 42,
                'value' => 'WCAST',
                'offset' => 1,
                'isdst' => 0,
                'name' => 'W. Central Africa Standard Time',
                'utc' => '["Africa\\/Lagos","Africa\\/Luanda","Africa\\/Porto-Novo","Africa\\/Kinshasa","Africa\\/Bangui","Africa\\/Brazzaville","Africa\\/Douala","Africa\\/Algiers","Africa\\/Libreville","Africa\\/Malabo","Africa\\/Niamey","Africa\\/Lagos","Africa\\/Ndjamena","Africa\\/Tunis","Etc\\/GMT-1"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+01:00) West Central Africa',
            ),
            42 => 
            array (
                'id' => 43,
                'value' => 'NST',
                'offset' => 1,
                'isdst' => 0,
                'name' => 'Namibia Standard Time',
                'utc' => '["Africa\\/Windhoek","Africa\\/Windhoek"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+01:00) Windhoek',
            ),
            43 => 
            array (
                'id' => 44,
                'value' => 'GDT',
                'offset' => 3,
                'isdst' => 1,
                'name' => 'GTB Standard Time',
                'utc' => '["Europe\\/Bucharest","Asia\\/Nicosia","Europe\\/Athens","Europe\\/Chisinau","Europe\\/Bucharest"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+02:00) Athens, Bucharest',
            ),
            44 => 
            array (
                'id' => 45,
                'value' => 'MEDT',
                'offset' => 3,
                'isdst' => 1,
                'name' => 'Middle East Standard Time',
                'utc' => '["Asia\\/Beirut","Asia\\/Beirut"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+02:00) Beirut',
            ),
            45 => 
            array (
                'id' => 46,
                'value' => 'EST',
                'offset' => 2,
                'isdst' => 0,
                'name' => 'Egypt Standard Time',
                'utc' => '["Africa\\/Cairo","Africa\\/Cairo"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+02:00) Cairo',
            ),
            46 => 
            array (
                'id' => 47,
                'value' => 'SDT',
                'offset' => 3,
                'isdst' => 1,
                'name' => 'Syria Standard Time',
                'utc' => '["Asia\\/Damascus","Asia\\/Damascus"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+02:00) Damascus',
            ),
            47 => 
            array (
                'id' => 48,
                'value' => 'EEDT',
                'offset' => 3,
                'isdst' => 1,
                'name' => 'E. Europe Standard Time',
                'utc' => 'NULL',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+02:00) E. Europe',
            ),
            48 => 
            array (
                'id' => 49,
                'value' => 'SAST',
                'offset' => 2,
                'isdst' => 0,
                'name' => 'South Africa Standard Time',
                'utc' => '["Africa\\/Johannesburg","Africa\\/Bujumbura","Africa\\/Gaborone","Africa\\/Lubumbashi","Africa\\/Maseru","Africa\\/Blantyre","Africa\\/Maputo","Africa\\/Kigali","Africa\\/Mbabane","Africa\\/Johannesburg","Africa\\/Lusaka","Africa\\/Harare","Etc\\/GMT-2"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+02:00) Harare, Pretoria',
            ),
            49 => 
            array (
                'id' => 50,
                'value' => 'FDT',
                'offset' => 3,
                'isdst' => 1,
                'name' => 'FLE Standard Time',
                'utc' => '["Europe\\/Kiev","Europe\\/Mariehamn","Europe\\/Sofia","Europe\\/Tallinn","Europe\\/Helsinki","Europe\\/Vilnius","Europe\\/Riga","Europe\\/Kiev Europe\\/Uzhgorod Europe\\/Zaporozhye"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
            ),
            50 => 
            array (
                'id' => 51,
                'value' => 'TDT',
                'offset' => 3,
                'isdst' => 1,
                'name' => 'Turkey Standard Time',
                'utc' => '["Europe\\/Istanbul","Europe\\/Istanbul"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+02:00) Istanbul',
            ),
            51 => 
            array (
                'id' => 52,
                'value' => 'JDT',
                'offset' => 3,
                'isdst' => 1,
                'name' => 'Israel Standard Time',
                'utc' => '["Asia\\/Jerusalem","Asia\\/Jerusalem"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+02:00) Jerusalem',
            ),
            52 => 
            array (
                'id' => 53,
                'value' => 'LST',
                'offset' => 2,
                'isdst' => 0,
                'name' => 'Libya Standard Time',
                'utc' => '["Africa\\/Tripoli","Africa\\/Tripoli"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+02:00) Tripoli',
            ),
            53 => 
            array (
                'id' => 54,
                'value' => 'JST',
                'offset' => 3,
                'isdst' => 0,
                'name' => 'Jordan Standard Time',
                'utc' => '["Asia\\/Amman","Asia\\/Amman"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+03:00) Amman',
            ),
            54 => 
            array (
                'id' => 55,
                'value' => 'AST',
                'offset' => 3,
                'isdst' => 0,
                'name' => 'Arabic Standard Time',
                'utc' => '["Asia\\/Baghdad","Asia\\/Baghdad"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+03:00) Baghdad',
            ),
            55 => 
            array (
                'id' => 56,
                'value' => 'KST',
                'offset' => 3,
                'isdst' => 0,
                'name' => 'Kaliningrad Standard Time',
                'utc' => '["Europe\\/Kaliningrad","Europe\\/Minsk","Europe\\/Kaliningrad"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+03:00) Kaliningrad, Minsk',
            ),
            56 => 
            array (
                'id' => 57,
                'value' => 'AST',
                'offset' => 3,
                'isdst' => 0,
                'name' => 'Arab Standard Time',
                'utc' => '["Asia\\/Riyadh","Asia\\/Bahrain","Asia\\/Kuwait","Asia\\/Qatar","Asia\\/Riyadh","Asia\\/Aden"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+03:00) Kuwait, Riyadh',
            ),
            57 => 
            array (
                'id' => 58,
                'value' => 'EAST',
                'offset' => 3,
                'isdst' => 0,
                'name' => 'E. Africa Standard Time',
                'utc' => '["Africa\\/Nairobi","Antarctica\\/Syowa","Africa\\/Djibouti","Africa\\/Asmera","Africa\\/Addis_Ababa","Africa\\/Nairobi","Indian\\/Comoro","Indian\\/Antananarivo","Africa\\/Khartoum","Africa\\/Mogadishu","Africa\\/Juba","Africa\\/Dar_es_Salaam","Africa\\/Kampala","Indian\\/Mayotte","Etc\\/GMT-3"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+03:00) Nairobi',
            ),
            58 => 
            array (
                'id' => 59,
                'value' => 'IDT',
                'offset' => 5,
                'isdst' => 1,
                'name' => 'Iran Standard Time',
                'utc' => '["Asia\\/Tehran","Asia\\/Tehran"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+03:30) Tehran',
            ),
            59 => 
            array (
                'id' => 60,
                'value' => 'AST',
                'offset' => 4,
                'isdst' => 0,
                'name' => 'Arabian Standard Time',
                'utc' => '["Asia\\/Dubai","Asia\\/Dubai","Asia\\/Muscat","Etc\\/GMT-4"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+04:00) Abu Dhabi, Muscat',
            ),
            60 => 
            array (
                'id' => 61,
                'value' => 'ADT',
                'offset' => 5,
                'isdst' => 1,
                'name' => 'Azerbaijan Standard Time',
                'utc' => '["Asia\\/Baku","Asia\\/Baku"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+04:00) Baku',
            ),
            61 => 
            array (
                'id' => 62,
                'value' => 'RST',
                'offset' => 4,
                'isdst' => 0,
                'name' => 'Russian Standard Time',
                'utc' => '["Europe\\/Moscow","Europe\\/Moscow Europe\\/Samara Europe\\/Simferopol Europe\\/Volgograd"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+04:00) Moscow, St. Petersburg, Volgograd',
            ),
            62 => 
            array (
                'id' => 63,
                'value' => 'MST',
                'offset' => 4,
                'isdst' => 0,
                'name' => 'Mauritius Standard Time',
                'utc' => '["Indian\\/Mauritius","Indian\\/Mauritius","Indian\\/Reunion","Indian\\/Mahe"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+04:00) Port Louis',
            ),
            63 => 
            array (
                'id' => 64,
                'value' => 'GST',
                'offset' => 4,
                'isdst' => 0,
                'name' => 'Georgian Standard Time',
                'utc' => '["Asia\\/Tbilisi","Asia\\/Tbilisi"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+04:00) Tbilisi',
            ),
            64 => 
            array (
                'id' => 65,
                'value' => 'CST',
                'offset' => 4,
                'isdst' => 0,
                'name' => 'Caucasus Standard Time',
                'utc' => '["Asia\\/Yerevan","Asia\\/Yerevan"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+04:00) Yerevan',
            ),
            65 => 
            array (
                'id' => 66,
                'value' => 'AST',
                'offset' => 5,
                'isdst' => 0,
                'name' => 'Afghanistan Standard Time',
                'utc' => '["Asia\\/Kabul","Asia\\/Kabul"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+04:30) Kabul',
            ),
            66 => 
            array (
                'id' => 67,
                'value' => 'WAST',
                'offset' => 5,
                'isdst' => 0,
                'name' => 'West Asia Standard Time',
                'utc' => '["Asia\\/Tashkent","Antarctica\\/Mawson","Asia\\/Oral Asia\\/Aqtau Asia\\/Aqtobe","Indian\\/Maldives","Indian\\/Kerguelen","Asia\\/Dushanbe","Asia\\/Ashgabat","Asia\\/Tashkent Asia\\/Samarkand","Etc\\/GMT-5"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+05:00) Ashgabat, Tashkent',
            ),
            67 => 
            array (
                'id' => 68,
                'value' => 'PST',
                'offset' => 5,
                'isdst' => 0,
                'name' => 'Pakistan Standard Time',
                'utc' => '["Asia\\/Karachi","Asia\\/Karachi"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+05:00) Islamabad, Karachi',
            ),
            68 => 
            array (
                'id' => 69,
                'value' => 'IST',
                'offset' => 6,
                'isdst' => 0,
                'name' => 'India Standard Time',
                'utc' => '["Asia\\/Calcutta","Asia\\/Calcutta"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
            ),
            69 => 
            array (
                'id' => 70,
                'value' => 'SLST',
                'offset' => 6,
                'isdst' => 0,
                'name' => 'Sri Lanka Standard Time',
                'utc' => '["Asia\\/Colombo","Asia\\/Colombo"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+05:30) Sri Jayawardenepura',
            ),
            70 => 
            array (
                'id' => 71,
                'value' => 'NST',
                'offset' => 6,
                'isdst' => 0,
                'name' => 'Nepal Standard Time',
                'utc' => '["Asia\\/Katmandu","Asia\\/Katmandu"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+05:45) Kathmandu',
            ),
            71 => 
            array (
                'id' => 72,
                'value' => 'CAST',
                'offset' => 6,
                'isdst' => 0,
                'name' => 'Central Asia Standard Time',
                'utc' => '["Asia\\/Almaty","Antarctica\\/Vostok","Asia\\/Urumqi","Indian\\/Chagos","Asia\\/Bishkek","Asia\\/Almaty Asia\\/Qyzylorda","Etc\\/GMT-6"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+06:00) Astana',
            ),
            72 => 
            array (
                'id' => 73,
                'value' => 'BST',
                'offset' => 6,
                'isdst' => 0,
                'name' => 'Bangladesh Standard Time',
                'utc' => '["Asia\\/Dhaka","Asia\\/Dhaka","Asia\\/Thimphu"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+06:00) Dhaka',
            ),
            73 => 
            array (
                'id' => 74,
                'value' => 'EST',
                'offset' => 6,
                'isdst' => 0,
                'name' => 'Ekaterinburg Standard Time',
                'utc' => '["Asia\\/Yekaterinburg","Asia\\/Yekaterinburg"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+06:00) Ekaterinburg',
            ),
            74 => 
            array (
                'id' => 75,
                'value' => 'MST',
                'offset' => 7,
                'isdst' => 0,
                'name' => 'Myanmar Standard Time',
                'utc' => '["Asia\\/Rangoon","Indian\\/Cocos","Asia\\/Rangoon"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+06:30) Yangon (Rangoon)',
            ),
            75 => 
            array (
                'id' => 76,
                'value' => 'SAST',
                'offset' => 7,
                'isdst' => 0,
                'name' => 'SE Asia Standard Time',
                'utc' => '["Asia\\/Bangkok","Antarctica\\/Davis","Indian\\/Christmas","Asia\\/Jakarta Asia\\/Pontianak","Asia\\/Phnom_Penh","Asia\\/Vientiane","Asia\\/Hovd","Asia\\/Bangkok","Asia\\/Saigon","Etc\\/GMT-7"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+07:00) Bangkok, Hanoi, Jakarta',
            ),
            76 => 
            array (
                'id' => 77,
                'value' => 'NCAST',
                'offset' => 7,
                'isdst' => 0,
                'name' => 'N. Central Asia Standard Time',
                'utc' => '["Asia\\/Novosibirsk","Asia\\/Novosibirsk Asia\\/Novokuznetsk Asia\\/Omsk"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+07:00) Novosibirsk',
            ),
            77 => 
            array (
                'id' => 78,
                'value' => 'CST',
                'offset' => 8,
                'isdst' => 0,
                'name' => 'China Standard Time',
                'utc' => '["Asia\\/Shanghai","Asia\\/Shanghai","Asia\\/Hong_Kong","Asia\\/Macau"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
            ),
            78 => 
            array (
                'id' => 79,
                'value' => 'NAST',
                'offset' => 8,
                'isdst' => 0,
                'name' => 'North Asia Standard Time',
                'utc' => '["Asia\\/Krasnoyarsk","Asia\\/Krasnoyarsk"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+08:00) Krasnoyarsk',
            ),
            79 => 
            array (
                'id' => 80,
                'value' => 'MPST',
                'offset' => 8,
                'isdst' => 0,
                'name' => 'Singapore Standard Time',
                'utc' => '["Asia\\/Singapore","Asia\\/Brunei","Asia\\/Makassar","Asia\\/Kuala_Lumpur Asia\\/Kuching","Asia\\/Manila","Asia\\/Singapore","Etc\\/GMT-8"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+08:00) Kuala Lumpur, Singapore',
            ),
            80 => 
            array (
                'id' => 81,
                'value' => 'WAST',
                'offset' => 8,
                'isdst' => 0,
                'name' => 'W. Australia Standard Time',
                'utc' => '["Australia\\/Perth","Antarctica\\/Casey","Australia\\/Perth"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+08:00) Perth',
            ),
            81 => 
            array (
                'id' => 82,
                'value' => 'TST',
                'offset' => 8,
                'isdst' => 0,
                'name' => 'Taipei Standard Time',
                'utc' => '["Asia\\/Taipei","Asia\\/Taipei"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+08:00) Taipei',
            ),
            82 => 
            array (
                'id' => 83,
                'value' => 'UST',
                'offset' => 8,
                'isdst' => 0,
                'name' => 'Ulaanbaatar Standard Time',
                'utc' => '["Asia\\/Ulaanbaatar","Asia\\/Ulaanbaatar Asia\\/Choibalsan"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+08:00) Ulaanbaatar',
            ),
            83 => 
            array (
                'id' => 84,
                'value' => 'NAEST',
                'offset' => 9,
                'isdst' => 0,
                'name' => 'North Asia East Standard Time',
                'utc' => '["Asia\\/Irkutsk","Asia\\/Irkutsk"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+09:00) Irkutsk',
            ),
            84 => 
            array (
                'id' => 85,
                'value' => 'TST',
                'offset' => 9,
                'isdst' => 0,
                'name' => 'Tokyo Standard Time',
                'utc' => '["Asia\\/Tokyo","Asia\\/Jayapura","Asia\\/Tokyo","Pacific\\/Palau","Asia\\/Dili","Etc\\/GMT-9"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+09:00) Osaka, Sapporo, Tokyo',
            ),
            85 => 
            array (
                'id' => 86,
                'value' => 'KST',
                'offset' => 9,
                'isdst' => 0,
                'name' => 'Korea Standard Time',
                'utc' => '["Asia\\/Seoul","Asia\\/Pyongyang","Asia\\/Seoul"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+09:00) Seoul',
            ),
            86 => 
            array (
                'id' => 87,
                'value' => 'CAST',
                'offset' => 10,
                'isdst' => 0,
                'name' => 'Cen. Australia Standard Time',
                'utc' => '["Australia\\/Adelaide","Australia\\/Adelaide Australia\\/Broken_Hill"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+09:30) Adelaide',
            ),
            87 => 
            array (
                'id' => 88,
                'value' => 'ACST',
                'offset' => 10,
                'isdst' => 0,
                'name' => 'AUS Central Standard Time',
                'utc' => '["Australia\\/Darwin","Australia\\/Darwin"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+09:30) Darwin',
            ),
            88 => 
            array (
                'id' => 89,
                'value' => 'EAST',
                'offset' => 10,
                'isdst' => 0,
                'name' => 'E. Australia Standard Time',
                'utc' => '["Australia\\/Brisbane","Australia\\/Brisbane Australia\\/Lindeman"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+10:00) Brisbane',
            ),
            89 => 
            array (
                'id' => 90,
                'value' => 'AEST',
                'offset' => 10,
                'isdst' => 0,
                'name' => 'AUS Eastern Standard Time',
                'utc' => '["Australia\\/Sydney","Australia\\/Sydney Australia\\/Melbourne"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+10:00) Canberra, Melbourne, Sydney',
            ),
            90 => 
            array (
                'id' => 91,
                'value' => 'WPST',
                'offset' => 10,
                'isdst' => 0,
                'name' => 'West Pacific Standard Time',
                'utc' => '["Pacific\\/Port_Moresby","Antarctica\\/DumontDUrville","Pacific\\/Truk","Pacific\\/Guam","Pacific\\/Saipan","Pacific\\/Port_Moresby","Etc\\/GMT-10"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+10:00) Guam, Port Moresby',
            ),
            91 => 
            array (
                'id' => 92,
                'value' => 'TST',
                'offset' => 10,
                'isdst' => 0,
                'name' => 'Tasmania Standard Time',
                'utc' => '["Australia\\/Hobart","Australia\\/Hobart Australia\\/Currie"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+10:00) Hobart',
            ),
            92 => 
            array (
                'id' => 93,
                'value' => 'YST',
                'offset' => 10,
                'isdst' => 0,
                'name' => 'Yakutsk Standard Time',
                'utc' => '["Asia\\/Yakutsk","Asia\\/Yakutsk Asia\\/Chita Asia\\/Khandyga"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+10:00) Yakutsk',
            ),
            93 => 
            array (
                'id' => 94,
                'value' => 'CPST',
                'offset' => 11,
                'isdst' => 0,
                'name' => 'Central Pacific Standard Time',
                'utc' => '["Pacific\\/Guadalcanal","Antarctica\\/Macquarie","Pacific\\/Ponape Pacific\\/Kosrae","Pacific\\/Noumea","Pacific\\/Guadalcanal","Pacific\\/Efate","Etc\\/GMT-11"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+11:00) Solomon Is., New Caledonia',
            ),
            94 => 
            array (
                'id' => 95,
                'value' => 'VST',
                'offset' => 11,
                'isdst' => 0,
                'name' => 'Vladivostok Standard Time',
                'utc' => '["Asia\\/Vladivostok","Asia\\/Vladivostok Asia\\/Sakhalin Asia\\/Ust-Nera"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+11:00) Vladivostok',
            ),
            95 => 
            array (
                'id' => 96,
                'value' => 'NZST',
                'offset' => 12,
                'isdst' => 0,
                'name' => 'New Zealand Standard Time',
                'utc' => '["Pacific\\/Auckland","Antarctica\\/McMurdo","Pacific\\/Auckland"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+12:00) Auckland, Wellington',
            ),
            96 => 
            array (
                'id' => 97,
                'value' => 'U',
                'offset' => 12,
                'isdst' => 0,
                'name' => 'UTC+12',
                'utc' => '["Etc\\/GMT-12","Pacific\\/Tarawa","Pacific\\/Majuro Pacific\\/Kwajalein","Pacific\\/Nauru","Pacific\\/Funafuti","Pacific\\/Wake","Pacific\\/Wallis","Etc\\/GMT-12"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+12:00) Coordinated Universal Time+12',
            ),
            97 => 
            array (
                'id' => 98,
                'value' => 'FST',
                'offset' => 12,
                'isdst' => 0,
                'name' => 'Fiji Standard Time',
                'utc' => '["Pacific\\/Fiji","Pacific\\/Fiji"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+12:00) Fiji',
            ),
            98 => 
            array (
                'id' => 99,
                'value' => 'MST',
                'offset' => 12,
                'isdst' => 0,
                'name' => 'Magadan Standard Time',
                'utc' => '["Asia\\/Magadan","Asia\\/Magadan Asia\\/Anadyr Asia\\/Kamchatka Asia\\/Srednekolymsk"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+12:00) Magadan',
            ),
            99 => 
            array (
                'id' => 100,
                'value' => 'KDT',
                'offset' => 13,
                'isdst' => 1,
                'name' => 'Kamchatka Standard Time',
                'utc' => 'NULL',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+12:00) Petropavlovsk-Kamchatsky - Old',
            ),
            100 => 
            array (
                'id' => 101,
                'value' => 'TST',
                'offset' => 13,
                'isdst' => 0,
                'name' => 'Tonga Standard Time',
                'utc' => '["Pacific\\/Tongatapu","Pacific\\/Enderbury","Pacific\\/Fakaofo","Pacific\\/Tongatapu","Etc\\/GMT-13"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+13:00) Nuku\'alofa',
            ),
            101 => 
            array (
                'id' => 102,
                'value' => 'SST',
                'offset' => 13,
                'isdst' => 0,
                'name' => 'Samoa Standard Time',
                'utc' => '["Pacific\\/Apia","Pacific\\/Apia"]',
                'created_at' => NULL,
                'updated_at' => NULL,
            'text' => '(UTC+13:00) Samoa',
            ),
        ));
        
        
    }
}